name: auto_securo_admin
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  page_transition: ^1.1.7+6
  cached_network_image: ^3.0.0
  fancy_bottom_navigation: ^0.3.3
  qr_code_scanner: ^0.4.0
  flutter_screenutil: ^5.0.0
  image_picker: ^0.7.4
  camera: ^0.8.1
  path_provider: ^2.0.1
  intl: ^0.17.0

  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.4
  firebase_messaging: ^9.1.1
  firebase_storage: ^8.0.1
  firebase_ml_vision: ^0.11.0+2

  date_format: ^2.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
